
build:
	go build -o step0_repl Step0_repl/step0_repl.go
	go build -o step1_read_print Step1_read_print/step1_read_print.go
	mv step0_repl ../
	mv step1_read_print ../
Run:
	go build -o step0_repl Step0_repl/step0_repl.go
	go build -o step1_read_print Step1_read_print/step1_read_print.go
	./step0_repl
clean:
	go clean
	rm step0_repl/step0_repl