
build:
	go build -o step0_repl Step0_repl/step0_repl.go
	mv Step0_repl/step0_repl .
run:
	go build -o step0_repl Step0_repl/step0_repl.go
	./Step0_repl/step0_repl
clean:
	go clean
	rm step0_repl/step0_repl